### ISSUE TITLE
Making sure I'm doing the commit thing right (making the branch and stuff)

### ISSUE THREAD

**Issue by JessJodoin** [algonquindesign-grads/2021#1]
Hey @thomasjbradley 

I just wanted to make sure I was doing the commit/creating branches thing right?

I made a new branch called 'starter-files' and made my commits to that branch, now I'm not sure what I should do.
Do I need to do a 'compare & pull request'? And then I delete the branch?

**Comment by MacKenzieRose** [comment]
@JessJodoin 

I reviewed and merged your pull request, and so am closing this issue.

You should be safe to delete the branch from your local files, as the main branch now reflects your commits.
