### ISSUE TITLE
Done enough to publish?

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#110]
With #109 merged, I think we should probably look at making the site live, if that's okay with you @thomasjbradley?

I'd still like to work on it over the week (cleaning up the pattern library and adding the awards page content once our grad show is done); does that sound reasonable?

Tagging to keep y'all in the loop @MissMadore @JessJodoin

**Comment by thomasjbradley** [comment]
Alrighty! It’s going live right now!

The best thing about the web is you can always update it later!

**Comment by thomasjbradley** [comment]
![itsalive](https://user-images.githubusercontent.com/105192/115421540-0b4d1980-a1ca-11eb-9cce-cc475f005373.gif)
