### ISSUE TITLE
No poster on introduction video

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2021#111]
![Screen Shot 2021-04-20 at 10 56 50 AM](https://user-images.githubusercontent.com/105192/115418038-24080000-a1c7-11eb-86a6-c46e2c35a954.png)

I have autoplay disabled for everything in my browser & the intro video is just a blank white box.

**Comment by MacKenzieRose** [comment]
#114 adds a poster to the homepage video
