### ISSUE TITLE
No link to YouTube live stream

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2021#112]
I think we need a **big** link to the scheduled YouTube live stream on the homepage. That’s the first place I’m gonna look on Friday evening.

**Comment by MacKenzieRose** [comment]
Bigger than the `Grad Show` link in the nav?

**Comment by thomasjbradley** [comment]
Yeah, that goes to a Facebook event. Not to the YouTube live stream.

**Comment by thomasjbradley** [comment]
What about people without Facebook accounts?

**Comment by MacKenzieRose** [comment]
As soon as I get a link from @MissMadore, the plan is to put the YouTube live link there. Is that a good place, or are you thinking more another section on the homepage somewhere?

**Comment by thomasjbradley** [comment]
That works okay for me. Alternatively & also, maybe here:

![Screen Shot 2021-04-20 at 11 12 53 AM](https://user-images.githubusercontent.com/105192/115420823-764a2080-a1c9-11eb-8197-629bce29746b.png)

**Comment by MissMadore** [comment]
I agree with this approach, the label for the button would read "YouTube Live Event" or just "Live Event".

Additionally, I feel that the label for "Gradshow" up in the nav might be better labeled "Live Event"

**Comment by MacKenzieRose** [comment]
Live link is up 🎉
