### ISSUE TITLE
Video caption WebVtt fix

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2021#113]
Add this attribute to all video tags that use the caption tracks: `crossorigin="anonymous"`

```html
<video controls="" loop="" playsinline="" class="push" preload="auto" crossorigin="anonymous">
```

Should fix the problem. At least seems to work in my local tests.

**Comment by MacKenzieRose** [comment]
You're a scholar and a saint @thomasjbradley; captions are working on my end (desktop, Firefox) 🎉
