### ISSUE TITLE
When linking to Social Media, preview description still reads "Coming March 2021"

### ISSUE THREAD

**Issue by MissMadore** [algonquindesign-grads/2021#115]
Can someone please advise on where that information is noted? @thomasjbradley @MacKenzieRose

**Comment by MacKenzieRose** [comment]
That content is from the Coming Soon site, and is probably just cached elsewhere on servers. (Unless I hecked up the SEO stuff in this repository, which is also possible 🤡 )

**Comment by thomasjbradley** [comment]
Yep, a cache thing. I just cleared Facebook’s sharing cache so it should be good now.

**Comment by MissMadore** [comment]
Is this a step that I need to take locally? :')

**Comment by thomasjbradley** [comment]
Nope, shouldn’t be. Is your FB still wrong?

**Comment by HannahDelaney** [comment]
Yes, it still shows "Coming March 2021" on the FB messenger preview.

**Comment by MissMadore** [comment]
& instagram shares

**Comment by MacKenzieRose** [comment]
This issue resolved on my end; how is it for you now, @MissMadore ?

**Comment by thomasjbradley** [comment]
Seems to be working today. Any one else confirm?

**Comment by thomasjbradley** [comment]
Nevermind, I see @MacKenzieRose confirmed.

I think we can close this.

**Comment by MissMadore** [comment]
I am still seeing the wrong description, but I hope it's just me :')
