### ISSUE TITLE
Specialty filters not working

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#116]
Motion/print/UX/web filters aren't working on Safari on iPhone 8

**Comment by MissMadore** [comment]
Here's hoping #119 resolves this

**Comment by MacKenzieRose** [comment]
It resolved it on my end; waiting for confirmation from second tester.

**Comment by MacKenzieRose** [comment]
Second tester confirmed all the filters work on their end 🎉
