### ISSUE TITLE
Broken links on awards page

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2021#132]
The two top links for Hannah & MacKenzie are broken. Missing the starting `/` in the URL.

![Screen Shot 2021-04-27 at 12 09 08 PM](https://user-images.githubusercontent.com/105192/116275345-8b86f800-a751-11eb-8ecb-3a937f5bfccc.png)

**Comment by MissMadore** [comment]
PR created for fix! @MacKenzieRose or @thomasjbradley whenever you're able~
