### ISSUE TITLE
Secondary background color now showing through homepage images

### ISSUE THREAD

**Issue by MissMadore** [algonquindesign-grads/2021#134]
This is being caused by the img:not(.awarded-student > img) styling overriding everything, including the img:not(.rainbow-line) style that it is attached to, which is currently applied to these images to try and correct it.

Anyone have a good idea on how to separate and style the classes to keep our grey backgrounds grey and all others white as required?

**Comment by MacKenzieRose** [comment]
I think #135 solves this @MissMadore

**Comment by MissMadore** [comment]
Many thanks!
