### ISSUE TITLE
Tasklist - ongoing

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#14]
### General tasks
- [ ] Include all aria content (main tags are missing landmark roles)
- [ ] Make nice image descriptions for alt tags for profs
- [ ] Awards section on separate designer page?
- [x] Add more JavaScript to homepage filters so primary specialties show first (at top of list) when that specialty is selected (if we have time 😄 )
- [ ] adding an alt to the homepage video
- [ ] on mobile landscape, the buttons are kinda close together (but that’s definitely being nit-picky, they still look and function like they’re supposed to so meh) (templates 1245)
- [ ] At 2x text-size in Edge the first set of buttons (portfolio and meeting) bump into each other between small and medium screen sizes. Probably not a huge issue. These buttons also bump into each other at 100% in Safari between the same sizes.
- [ ] Layout 3: @ 1150ish px, project images 3 & 4 overlap student information card (Opera)
- [ ] Layout 3: similar tiny amount of overlap in the same spot, but student image card is in front, which is great (Firefox)
- [ ] Can we add a drop-shadow to all buttons? (branding)

---

- [x] Update quiz content:
Quiz content update:
Intro: 
This quiz was designed to help you connect with our designers.
Find a designer who is available for work, interested in networking, or requesting a portfolio review. By the end of the quiz, you will have a list of designers that match what you’re looking for!
Question 1 Answers:
Looking to Hire
Providing a Portfolio Review
Networking
- [x] ‘book a meeting’ buttons don’t lead to their calendly page but an error page saying the page could not be found and it has your (MacKenzie) name — bulk0002 — in the url. BUT this only happens after you complete the quiz, if you click ‘book a meeting’ before you’ve completed the quiz they go the right place
- [---] with CSS disabled, we get some weird stuffs happening and I’m not sure what all that ‘uk-size10’ stuff is but if goes on for a while (quiz page). **{Maggie: I didn't get this error? It seems to function normally when I disable the CSS in Firefox so I'm not sure what the issue is?}**
- [x] on the Quiz page, the footer has a weird padding on the left and right side
- [---] The Quiz page shows results on the starting page. Is this intentional? I don’t think they should be immediately viewable. Please remove if we can. (branding) --> would fix clickable issues with card links to MacKenzie's calendly **{Maggie: I spent a long time trying to fix this problem before placement started and I couldn't hide the results and then have them work properly. Showing / hiding the results from the main page screws up with the JS and sizing of the results and they end up not displaying properly when the "final results" are finally shown. Sorry }**
- [x] Fix text size `continuous learner` question 2 firefox desktop fullscreen

---
### Major pages/files to complete
- [x] Layout 1
- [x] Layout 2
- [x] Layout 3
- [x] Layout 4
- [x] Layout 5
- [x] Homepage
- [x] Quiz page
- [x] Completed student profiles
---
### When site is done
- [ ] Modify sitemap frequencies to never
- [x] Update Team member information
- [ ] Browser testing
- [ ] Accessibility testing 
- [ ] Clean up descriptions and previews in pattern library configs
- [x] Enable https ( any thoughts @thomasjbradley? )
- [ ] Add to patterns and pull content out of templates
- [ ] Add awards section (post grad show)
---
---
---
### Completed
- [x] Finish button patterns
- [x] Build headers 
- [x] Build footers
- [x] Modify sitewide footers to gray (rip)
- [x] Change secondary footers icon link colours
- [x] Build and test one markdown file
- [x] Make all student markdown files (rename?)
- [x] Hover state outlines are too sharp; if time, round them somehow
- [x] Add Sabrina's changes to her profile content
- [x] Update Jen's projects
- [x] Upload Hong's missing video projects
- [x] Replace Jess's headshot
- [x] Replace Sabrina's headshot
- [x] Add Sam Cossar's project descriptions
- [x] Make sure Chrisine's bio and quote are updated
- [x] fix uxui includes in md files
- [x] Upload Kaitlyn's new photo
- [x] Fix icon issue that occurs in layouts 2 and 4 (doesn't match header....) --> `social_icon_color` 
- [x] Need a youtube icon from branding for Taz's pattern; will need to update all templates as well. Le sigh
- [x] Need an Apple music icon for Kyle's pattern.... bigger sigh
- [x] Need an email icon for Daniela's pattern.... literally all the sighs
- [x] Add Youtube link to Kaitlyn's markdown
- [x] target blank to student card links
- [x] Add Jesse's dribble account to markdown
- [x] Update Khoi's motion piece
- [x] Wait for & upload proper export of Hong's video project 4 file
- [x] Add placeholder image from branding files
- [x] Hear back from co-chairs regarding Ziai's content
- [x] Add teacher content to site 
- [x] reexport svg gradient because it has whitespace
- [x] Ensure all markdown links are full URLS (ex https://)
- [x] Adjust quotations in patterns with {{if}} for author; make sure fixes extra spacing issues for " . "
- [x] template 3 fix project header fonts
- [x] Add new photo for Sarah; waiting to receive
- [x] Update Zach's headshot
- [x] Finish card patterns 
- [x] Janet headshot? --> will change if hear from Hannah
- [x] Sabrina reported that the description overlay for mp4 files interferes with the control bar (being able to play/pause/adjust sound etc) **ADDITIONALLY THEY INTERFERE WITH SEEING CAPTIONS** so the solution will be to pull the description out of the video div, and have it outside at all times. 
- [x] Project descriptions have inconsistent widths depending on length of content
- [x] Add updated motion piece to homepage
- [x] Replace Sabrina's intro video
- [x] Adjust size of the video on homepage because some people think it's a loading screen (branding said this isn't a problem)
- [x] the largest project images on the site are 1880 pixels wide, but were exported for 1568 --> reexport so not blurry or adjust patterns
- [x] Make sure video transcripts are included correctly (currently 34 correct files have been received and uploaded)
- [x] test and update new transcript files
- [x] Replace one of Quincy's images with a video file (waiting to receive)
- [x] Add data includes for social media buttons so they actually go to the sites...oops
- [x] Have to decide what to do about the removal of link text from pattern 3 for Ian (project 2)
- [x] Consider embedded video colour customizations --> decided not to pursue
- [x] Add all include content into markdown files
- [x] Post placement content? --> decided not to pursue
- [x] Replace Chelle's photo when new file is provided
- [x] Hover state of headers is always white, but probably should be black for the icon_black versions.
- [x] Tap trigger for descriptions? (branding) --> MacKenzie's a moron they do this automatically
- [x] Concerns about text colour contrast (for quotes for example) --> removed `quote-accent` class so all text should be primary colour; sorry branding, but accessibility comes first 🤷‍♀️ 
- [x] For videos, I see that the caption can’t be made to hover on top of the video. Since the description has to be below the video (that’s totally fine) can we make it only appear below when hovering the project? (branding)
- [x] Add if statements to specialty includes, because not all students listed 3 --> monica only 1
- [x] Add Janet 2019 headshot
- [x] Get approval for modifications to aforementioned headshot
- [x] Round all 4 corners of video description tags (chair request)
- [x] Remove extra content in Ziai markdown file
- [x] Line length of descriptions
- [x] footer support links go to the top of the page — will just need to steal href from header
- [x] Footer: Can we change the black GEN.A icon to the coloured version? And remove twitter icon from whole website (social team is not using it anymmore). (branding)
- [x] Fix the variable width of the `.rainbow-line` svg in student cards and portfolios; why is it doing that??
- [x] Can we make “Welcome To” a lighter weight? (just change to one thinner than whatever it is now [either medium or semi-bold] — just seems to compete with the date too much) (branding)
- [x] Is there a way to make these lines of text not have a widow for web size? Whatever the best way is to fix that if possible I trust your decision. (branding re Homepage)
- [x] Change navigation to incorporate YouTube Live (instead of Support?)
- [x] Upload all student content
- [x] On Safari & iPhone 5, on Jude’s profile, their specialities (Illustration, Motion, Branding) are super squished together, it looks like one word.
- [x] for a designer page with only two specializations present, the spacing isn't right or it isn't centered properly (e.g. using Cole's page as an example)
- [x] all quotes should be italicized. (branding) --> Someone want to confirm that's actually proper typesetting because MacKenzie is HELLA skeptical and does not fancy being murdered by Andrea or Greg
- [x] make sure to top button is z-indexed to top
- [x] to top button transition speed (if time) (easing??)
- [x] add `preload="auto"` to all intro video content
- [x] Remove links for prof cards
- [x] In layout 3 can we come up with a better solution for the project image sizes? (branding)
- [x] Can all button hover states on student profile pages be changed to the off-black background with white writing option? (branding)
- [x] If includes for quotes (see Ziai's page) --> could expand to most content so this page seems less empty?
- [x] Can hover outlines (for nav, social icons, etc.) be changed to have rounded corners? (branding) --> `icon-box-shadow` class in buttons.css -->Good news: they're round! Bad news: active states nest them and there's a padding/scale shift..... we'll call it a feature instead of a bug? 😬 
- [x] with images disabled, again, the alt tags on the headshots for some colours is hard to read (will probably just have to add a default black to the alt tags or something) (template 3)
- [x] Can we add a drop shadow to the scrolling profile section on this layout? (branding)
- [x] making the captions work --> Thomas thinks this will happen when the site goes live; will test after launch --> Praise be to our scholar and saint developer extraordinaire and sage mentor, Thomas, for getting these to work~
- [x] Add targets to external links so they open in a new tab or window, and don't navigate fully away from site --> nopenopenope
- [x] Make JavaScript filters work on homepage for iPhone 8 >:(
- [x] In Safari I can see a small white line in the “Looking for a Designer?” Section on the homepage, between the div that holds the text and the arrow at the bottom.

**Comment by JessJodoin** [comment]
Quotations in all italics? Yeaahhh, no. 

From what I remember, you shouldn't put full sentences in italics because it get hard to read for people. 
The only things you should be italicizing are single words you want to put more emphasis on, titles of work/art, foreign words (like ones in a different language), technical terms, publication names.. things like that

alsoooo... do we REALLY have to do the ugly ass drop shadow bs?

**Comment by MacKenzieRose** [comment]
Re: quotes; totally agree;

I'll nix the drop shadows, but we need to apply that `icon-box-shadow` class to all the button-y hovery stuff; and **uNfORtUnaTeLy** that means we already use the thing for drop shadows to do a different thing, so we can't do them. oops 🤷 🤡

**Comment by JessJodoin** [comment]
oh noooo..... how unfortunate...

**Comment by thomasjbradley** [comment]
> Add targets to external links so they open in a new tab or window, and don't navigate fully away from site

I would prefer you didn’t do that—for accessibility reasons.

> Enable https ( any thoughts @thomasjbradley? )

Will “just happen” when we go live.

**Comment by MacKenzieRose** [comment]
> I would prefer you didn’t do that—for accessibility reasons.

Even for social media links? I'm happy to revert them all back to standard links; a lot were added because branding decided against have a carousel option for looking through designer profiles quickly.

**Comment by thomasjbradley** [comment]
@MacKenzieRose Yeah. It should always be the user’s choice as to whether they want a new tab/window or not.

**Comment by MacKenzieRose** [comment]
Okay so branding/the chairs prefer if links to external content (ex. social media) remain `target="_blank"` but I won't add that into any internal links (like clicking on student cards). The best kind of compromise is when no one is happy? 😰

**Comment by thomasjbradley** [comment]
I heavily disagree with this decision. @MissMadore @HannahDelaney 

I’ve included resources below to inform my beliefs:

*Articles*
- https://css-tricks.com/use-target_blank/
- https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/

*Web Content Accessibility Guidelines:*
- https://www.w3.org/WAI/WCAG21/Techniques/general/G200
- https://www.w3.org/WAI/WCAG21/Techniques/general/G201
- https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR24

---

If we do follow through with it, we must close a massive security hole `target="_blank"` creates. Please add the following attributes to all `<a>` tags that open new windows/tabs: `rel="noopener noreferrer"`

```html
<a href="" target="_blank" rel="noopener noreferrer">
```

- https://web.dev/external-anchors-use-rel-noopener/
- https://medium.com/sedeo/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

**Comment by MissMadore** [comment]
I am willing to conceded to the best accessibility standards and work under the assumption that most of our users are smart enough to learn that their clicks will redirect them away from the page/site and start opening up new tabs/windows on their own. Target _blanks can go, and I am okay with that. If branding has qualms, then I can tackle them with Hannah. 

Seriously, how can I not follow the sassy-sage advice of the almighty CSS-tricks.com? You really know the way to my heart @thomasjbradley :shipit: 

Per their point on user-initiated media playing, this may apply if we have a bio or project video playing on a student profile for example. Given that the videos can be re-played and you can navigate to a specific point in a video, this may not pose too serious of an issue if a user accidentally clicks away through a social link. I wouldn't be opposed to having a redirect alert on external links, but also feel that it would be more than fine without.

**Comment by MacKenzieRose** [comment]
> I wouldn't be opposed to having a redirect alert on external links, but also feel that it would be more than fine without.

#117 removes links opening in new tabs; if we need to do redirect alerts, would love more direction on how that would work/where it would apply.
