### ISSUE TITLE
Making the hamburger icon stay in place

### ISSUE THREAD

**Issue by JessJodoin** [algonquindesign-grads/2021#24]
Hey @thomasjbradley 

I have just a quick question about the toggle nav in the header. 

So far I have it functioning and looking (sort of) how I want but when you click the toggle the icon moves up when the nav is showing and I was wondering if you knew a good way to make it stay put and have the `<ul>` push down from where is icon is.

Thanks!  👍

**Comment by thomasjbradley** [comment]
I don’t see the moving up, but I see the icon is moving horizontally. It’s centered within the navigation box.

![Screen Shot 2021-02-19 at 12 56 40 PM](https://user-images.githubusercontent.com/105192/108542652-01826500-72b2-11eb-80c2-0a4fcabef6e9.png)

![Screen Shot 2021-02-19 at 12 56 46 PM](https://user-images.githubusercontent.com/105192/108542656-02b39200-72b2-11eb-91e8-d9e5123ade48.png)

*As the navigation box gets wider—when the links show—the icon stays centered.*

```css
justify-content: flex-end;
align-items: flex-end;
```

Fixes that.

https://github.com/algonquindesign-grads/2021/pull/28#issuecomment-782235291

**Comment by JessJodoin** [comment]
Okay thanks! 😄  The only other issue I get with that is on the small size (320px) the close icon shifts too far over so we get the gross side scroll action

<img width="236" alt="Screen Shot 2021-02-19 at 1 10 08 PM" src="https://user-images.githubusercontent.com/43217543/108544013-d8fb6a80-72b3-11eb-9528-c6ed76dd40be.png">

<img width="253" alt="Screen Shot 2021-02-19 at 1 11 06 PM" src="https://user-images.githubusercontent.com/43217543/108544088-f3354880-72b3-11eb-862b-bffedaf80272.png">

**Comment by MacKenzieRose** [comment]
Since this seems resolved on my end (toggle is happy in Chrome and Firefox), I'm going to close this issue. Feel free to reopen if needed~

**Comment by thomasjbradley** [comment]
@JessJodoin I think the quick fix is to get rid of the left/right padding on `.h-nav-ul li`. The nav gets too wide to fit in a flex row beside the logo & therefore breaks out of the box to the right, causing the icon to shift with it.
