### ISSUE TITLE
css href in <head> tag of default.html layout

### ISSUE THREAD

**Issue by akhoinguyen** [algonquindesign-grads/2021#25]
Hey guys @JessJodoin @MacKenzieRose,
while coding I noticed inside the `default.html` file the css <link> aren't linked from the root css folder: 

<img width="572" alt="Screen Shot 2021-02-18 at 5 08 11 PM" src="https://user-images.githubusercontent.com/43136539/108428237-3d62ef00-720c-11eb-930e-f1d0b94c7b10.png">

Just something I thought worth pointing out.

**Comment by MacKenzieRose** [comment]
Hey @akhoinguyen 

Good catch 😄 Thank you!
