### ISSUE TITLE
Can't commit any changes from my own file

### ISSUE THREAD

**Issue by Maggie2744** [algonquindesign-grads/2021#47]
Hi! If anyone has any idea how to fix this Github Commit error, I'm all ears!
On my copy of the site, whenever I make my changes and attempt to commit them on Github Desktop app, I get an error: 

it states: "Author Identity Unknown"

<img width="542" alt="Screen Shot 2021-03-07 at 2 45 36 PM" src="https://user-images.githubusercontent.com/43113691/110252572-0e5eb400-7f54-11eb-9e9c-440f52d16445.png">

Just wondering if I'm doing something wrong when trying to commit the changes (it's probably an error on my end).

@thomasjbradley @MacKenzieRose

**Comment by thomasjbradley** [comment]
Have you tried signing out and signing back into your GitHub Desktop app?
Also, under `Preferences > Git` make sure your details are filled in.

**Comment by Maggie2744** [comment]
I am so embarrassed that I didn't try that haha woops. Thanks @thomasjbradley ! I don't know what I would do without your help.
