### ISSUE TITLE
Non-Urgent: Do Liquid includes add whitespace?

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#68]
@thomasjbradley

---
<img width="1358" alt="Screen Shot 2021-03-12 at 11 29 29 PM" src="https://user-images.githubusercontent.com/19557909/111019064-deb40f80-838a-11eb-9738-34954ba8b2f4.png">

<img width="561" alt="Screen Shot 2021-03-12 at 11 33 02 PM" src="https://user-images.githubusercontent.com/19557909/111019151-541fe000-838b-11eb-90fc-99238aefaca0.png">

We've had requests to fix the space before the closing quotation mark (see above), but the quotes as typed into the Markdown files don't have whitespace there. Is that a function of using Liquid includes, or am I missing something?

**Comment by thomasjbradley** [comment]
It looks like it is coming from the Markdown, because of using `|` style paragraphs.

Try doing this: 

`{{include.data.quote_text|strip}}`

**Comment by MacKenzieRose** [comment]
Cool! Thank you :) I never thought to try actually reading about other Liquid filters; throw that on the to-do list pile 😆
