### ISSUE TITLE
Grad Site Homepage Filtering

### ISSUE THREAD

**Issue by JessJodoin** [algonquindesign-grads/2021#75]
Hey @thomasjbradley 

I have some questions about how I should go about coding the homepage filters.

When you say add the `data-` attribute to the `<a>` tags, do you mean on the `<a>` tags on student cards or on the filter `<a>` tags or both?

Also when the selected filter option displays/highlights the matching students. So, what I was was sort of picturing with the filtering is that when you click an option, say motion, all the people with motion as their primary specialty will have their background change from the grey they currently are to our tint variable (so for motion, a light green) so that our hover states still function. 

How should I do that? Can I even do that? LOL

Thanks again for all your help! (and patience with my slow ass brain) 😃 👍

**Comment by thomasjbradley** [comment]
> When you say add the data- attribute to the <a> tags, do you mean on the <a> tags on student cards or on the filter <a> tags or both?

On the student cards only.

> changing colour

To make that happen you’d want to be adding & removing classes from the student cards. Create a class called like `.filtered-motion` that has the correct background colour.

Then, when clicking on motion button, you have to perform these JS tasks:

1. Remove all the old filtered classes
2. Select the correctly filtered things & add the new class

```js
$("#motion-btn").on("click", function () {
  $(".filtered-web").removeClass("filtered-web"); // Repeat line for all filter types
  $(".home-card-grid > a[data-filter='motion']").addClass("filtered-motion");
});
```

**Comment by JessJodoin** [comment]
YAY! Thank you, I have them filtering now, but I've run into another issue.

The background colour isn't showing up, unless I add `!important` to the `.filtered-` classes but if I do that the hove stops working. So should I just add a hover state to those `.filtered-` classes or is there a better way to achieve this?

**Comment by thomasjbradley** [comment]
What’s the selector like for the student card `<a>` tags themselves? Are the multiple pieces?

Like: `.home-card-grid a`?

If so, you’ll need to be equally as specific: `.home-card-grid .filtered-web`.

And yeah, you’ll likely also have to add a hover state too.

**Comment by JessJodoin** [comment]
In my js file I target it like this

`$('.home-card-grid > a[data-category~="print"] .student-card-photo img').addClass('filtered-print');`

**Comment by thomasjbradley** [comment]
I meant, in the CSS. Like what’s the CSS selector that is currently applying the background?

**Comment by JessJodoin** [comment]
Oh my bad.

```
img:not(.rainbow-line) {
  background-color: var(--color-secondary);
  border-radius: 10px;
}
```

**Comment by thomasjbradley** [comment]
Okay. So, then you’d need to extend against that selector:

```css
img:not(.rainbow-line).filtered-print {
}
```

**Comment by JessJodoin** [comment]
Oooooh okay I'll try that 😄 Thank you!
