### ISSUE TITLE
Browser Testing — Maggie

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#83]
# Browser Testing
Welcome to browser testing, @maggie2744. 

I have assigned you the following list of browsers to test [the website](https://determined-yonath-0381f1.netlify.app/) on. Please check things off as you complete them.

Additionally, please document any concerns you encounter during testing in this issue thread, and include any relevant supporting documentation, including screenshots 🙂 

---
### iPad
- [x] Opera on iPad Pro
- [x] Safari on iPad Pro
- [x] Chrome on iPad Pro

---
### Mobile
- [x] Safari on iPhone 11

---
### Checklist for each browser tested:
- [x] Test home page (including student filters)
- [x] Test quiz page
- [x] Test Dawson student page (template 2)
- [x] Test Cole student page (template 4)
- [x] Test Brianna student page (template 1)
- [x] Test Ian student page (template 3)
- [x] Test Jude student page (template 5)
- [x] Test wrong page (to test 404)
—
- [x] Test all screen widths
- [x] Test all screen heights
- [x] Test fullscreen
- [x] Test mobile portrait
- [x] Test mobile landscape
—
- [x] Test with font sizes 2x smaller
- [x] Test with font sizes 2x bigger
- [x] Test with images disabled
- [x] Test with CSS disabled

---
---
---
Deadline: Saturday, March 20th, 11:59PM
---
---
---

**Comment by Maggie2744** [comment]
Hi @MacKenzieRose !

Here are some things to mention from my browser testing:

**1) On all three browsers and present on the iPad and iPhone 11:**
-> on the main page, the filters filtering out the designers also filters out the teachers
-> For Cole's page (template 4): on his first project, it is lacking a description.
-> clicking on the Teacher cards takes the user to a blank web page
-> the 404 page looks great and stylized properly but it doesn't come up when it needs to (e.g. when selecting one of the teacher's cards)


**2) For Opera, Chrome and Safari on the iPad Pro:**
-> for Ian's page (template 3), when my iPad is on horizontal view it squishes the main views of the first two example pieces. When the iPad is in vertical view, this doesn't happen
![IMG_1154](https://user-images.githubusercontent.com/43113691/111706610-f4a55280-8818-11eb-95d4-a8c319a7e59b.PNG)


**3) On Safari browser for iPhone 11:**
-> on the Quiz page, the footer has a weird padding on the left and right side
![IMG_7331](https://user-images.githubusercontent.com/43113691/111706526-d2133980-8818-11eb-8267-40a9bec4aca0.PNG)

-> for a designer page with only two specializations present, the spacing isn't right or it isn't centered properly (e.g. using Cole's page as an example)
![IMG_7332](https://user-images.githubusercontent.com/43113691/111706535-d5a6c080-8818-11eb-9e7c-a99357f2459d.PNG)
