### ISSUE TITLE
Browser Testing — Treawna

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#84]
# Browser Testing
Welcome to browser testing, @trebird. 

I have assigned you the following list of browsers to test [the website](https://determined-yonath-0381f1.netlify.app/) on. Please check things off as you complete them.

Additionally, please document any concerns you encounter during testing in this issue thread, and include any relevant supporting documentation, including screenshots 🙂 

---
### Desktop
- [x] Opera on MacBook
- [x] Firefox on MacBook

---
### Mobile
- [x] Opera Mini on iPhone 7
- [x] Chrome on iPhone 7
---
### Checklist for each browser tested:
- [x] Test home page (including student filters)
- [x] Test quiz page
- [x] Test Dawson student page (template 2)
- [x] Test Cole student page (template 4)
- [x] Test Brianna student page (template 1)
- [x] Test Ian student page (template 3)
- [x] Test Jude student page (template 5)
- [x] Test wrong page (to test 404)
—
- [x] Test all screen widths
- [x] Test all screen heights
- [x] Test fullscreen
- [x] Test mobile portrait
- [x] Test mobile landscape
—
- [x] Test with font sizes 2x smaller
- [x] Test with font sizes 2x bigger
- [x] Test with images disabled
- [x] Test with CSS disabled

---
---
---
Deadline: Saturday, March 20th, 11:59PM
---
---
---

**Comment by trebird** [comment]
Hi @MacKenzieRose,

Thank you for your patience! Here are my testing results. The website is amazing! Please let me know if I can help with anything. 

### Opera on MacBook
- Layout 3: @ 1150ish px, project images 3 & 4 overlap student information card
<img width="891" alt="Screen Shot 2021-03-24 at 7 04 33 PM" src="https://user-images.githubusercontent.com/43139113/112400617-23bb3880-8cdf-11eb-91b3-8b12806ed5f4.png">

- Layout 3: Ian's project 2 image & text not behaving properly / overlapped by his student information card *also on chrome desktop, but not in firefox!
<img width="877" alt="Screen Shot 2021-03-24 at 6 56 11 PM" src="https://user-images.githubusercontent.com/43139113/112400545-f66e8a80-8cde-11eb-8518-a6573643cb20.png">

### Firefox on MacBook
- Layout 3: similar tiny amount of overlap in the same spot, but student image card is in front, which is great
<img width="886" alt="Screen Shot 2021-03-24 at 8 28 27 PM" src="https://user-images.githubusercontent.com/43139113/112400811-87ddfc80-8cdf-11eb-94e5-256f5ac1c320.png">

### Opera Browser on iPhone 7
-student pages 1, 2 and 4: student info card cta buttons squished in lanscape orientation

### Chrome on iPhone 7
-student pages 1, 2 and 4: student info card cta buttons squished in lanscape orientation

### Universal
- footer **support** links go to the top of the page — will just need to steal href from header
- no visible behance icon
<img width="554" alt="behance-icon" src="https://user-images.githubusercontent.com/43139113/112400875-b0fe8d00-8cdf-11eb-9222-3ab15a9dde94.png">
- Student pages info card cta buttons squish on desktop for layouts 1,2, 4 and 5 from 608 – 730ish px
<img width="347" alt="Screen Shot 2021-03-24 at 6 49 51 PM" src="https://user-images.githubusercontent.com/43139113/112400860-a9d77f00-8cdf-11eb-8a34-2bc47941c759.png">
- Not sure if intended, but hover states for videos appear beneath the video
<img width="593" alt="Screen Shot 2021-03-24 at 6 57 25 PM" src="https://user-images.githubusercontent.com/43139113/112400942-d68b9680-8cdf-11eb-9b80-8b385e822aff.png">

### Misc
- *for social / branding, but just making note in case I forget — not sure if we're on [twitter](https://twitter.com/algonquindesign/) this year, but it's still branded for 2020
