### ISSUE TITLE
Browser Testing — Khoi

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#85]
# Browser Testing
Welcome to browser testing, @akhoinguyen. 

I have assigned you the following list of browsers to test [the website](https://determined-yonath-0381f1.netlify.app/) on. Please check things off as you complete them.

Additionally, please document any concerns you encounter during testing in this issue thread, and include any relevant supporting documentation, including screenshots 🙂 

---
### Desktop
- [x] Yandex on MacBook

---
### iPad
- [x] Safari on iPad mini
- [x] Firefox on iPad mini
- [x] Chrome on iPad mini

---
### Checklist for each browser tested:
- [x] Test home page (including student filters)
- [x] Test quiz page
- [x] Test Dawson student page (template 2)
- [x] Test Cole student page (template 4)
- [x] Test Brianna student page (template 1)
- [x] Test Ian student page (template 3)
- [x] Test Jude student page (template 5)
- [x] Test wrong page (to test 404)
—
- [x] Test all screen widths
- [x] Test all screen heights
- [x] Test fullscreen
- [x] Test mobile portrait
- [x] Test mobile landscape
—
- [x] Test with font sizes 2x smaller
- [x] Test with font sizes 2x bigger
- [x] Test with images disabled
- [x] Test with CSS disabled

---
---
---
Deadline: Saturday, March 20th, 11:59PM
---
---
---

**Comment by akhoinguyen** [comment]
Hey sorry for the delay there! Hopefully I can still contribute :(
Here are some problems I found while testing:

### Homepage
- The homepage video is a little slow to load
- The Quiz section divider has some issue on tablet landscape mode:
![IMG_0757](https://user-images.githubusercontent.com/43136539/113192857-4b555800-922d-11eb-9c31-04462e8ec29e.jpg)

### Template 1
- Same as homepage with the Quiz divider on homepage ^

### Template 3
- Content display issue on tablet landscape mode
![IMG_0758](https://user-images.githubusercontent.com/43136539/113193736-5066d700-922e-11eb-8f7c-fbfc862ac8e2.jpg)
