### ISSUE TITLE
Quiz page top-nav doesn’t work

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2021#87]
Clicking on “Designers” or “Support” doesn’t go to the home page and link downwards.

Missing `/` at the start of these 2 jump links:
https://github.com/algonquindesign-grads/2021/blob/main/_patterns/header/secondary-header.html#L15-L16

Also, “Support” doesn’t go anywhere.

**Comment by MacKenzieRose** [comment]
Latest merge ( #88 ) resolved this. 

Thanks @thomasjbradley; onto the other 28734827 things wrong with the site 🤡
