### ISSUE TITLE
2 Questions relating to video

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#99]
Hi @thomasjbradley 

Two questions:
1. The intro video captions don't seem to work anymore, and I can't figure out why. Do you have any suggestions of things I can try?
2. The video content loads SO slowly; should I run all of the videos through something like Handbrake (a supposedly lossless compressor), or could that affect the encoding (and therefore the ability of browsers to serve the videos)?

Hope all is well. Thanks for your help :)

**Comment by thomasjbradley** [comment]
2. The videos do look pretty large in size. I downloaded one of them and ran it through Handbrake and it did get slightly smaller. Might be worth trying a few more on some of the larger sizes to see if it helps.

**Comment by thomasjbradley** [comment]
*I also noticed a bunch of files outside the `2021` folder that should be moved.*

**Comment by thomasjbradley** [comment]
1. I’m getting a security error in the console when trying to load the WebVTT files. Probably because it’s trying to load cross-domain. As in the `netlify.app` domain doesn’t match the `grads.images` domain.

I think it’ll probably start working when we move to the live domain. I think…

**Comment by MacKenzieRose** [comment]
> _I also noticed a bunch of files outside the `2021` folder that should be moved._

<img width="601" alt="Screen Shot 2021-04-15 at 7 18 52 PM" src="https://user-images.githubusercontent.com/19557909/114949659-717b1a80-9e1f-11eb-98cf-222262caa76e.png">

Where do you see those?

**Comment by MacKenzieRose** [comment]
>     1. I’m getting a security error in the console when trying to load the WebVTT files. Probably because it’s trying to load cross-domain. As in the `netlify.app` domain doesn’t match the `grads.images` domain.
> 
> 
> I think it’ll probably start working when we move to the live domain. I think…

If not, I'll keep troubleshooting when the site is up 😄; additionally, we wanted to add these awards we're doing to the site, but after our grad show (so we don't ruin the surprise). Is it okay if I modify the site a little after the 23rd?

**Comment by MacKenzieRose** [comment]
>     1. The videos do look pretty large in size. I downloaded one of them and ran it through Handbrake and it did get slightly smaller. Might be worth trying a few more on some of the larger sizes to see if it helps.

Any export settings you would suggest in Handbrake, or should I bother one of our motion teachers about that?

**Comment by thomasjbradley** [comment]
Weird about the files, this is what I see:

![Screen Shot 2021-04-15 at 10 14 02 PM](https://user-images.githubusercontent.com/105192/114961985-e8bca880-9e37-11eb-8094-d7f968033bd9.png)

**Comment by thomasjbradley** [comment]
Handbrake encoding:

![Screen Shot 2021-04-15 at 10 14 47 PM](https://user-images.githubusercontent.com/105192/114962038-02f68680-9e38-11eb-9e04-480b9aaba096.png)

**Comment by thomasjbradley** [comment]
> If not, I'll keep troubleshooting when the site is up 😄; additionally, we wanted to add these awards we're doing to the site, but after our grad show (so we don't ruin the surprise). Is it okay if I modify the site a little after the 23rd?

Yeah, no problem. I usually wait a little while to revoke everyone’s credentials.

**Comment by MacKenzieRose** [comment]
> Handbrake encoding:
> 
> ![Screen Shot 2021-04-15 at 10 14 47 PM](https://user-images.githubusercontent.com/105192/114962038-02f68680-9e38-11eb-9e04-480b9aaba096.png)

So the intro videos are definitely the worst offenders; for the ones that are still over 100MB after the first Handbrake compression, do you think I should recompress them at 720p? Could we do something like `srcset` and `sizes` but for video, so the mobile load is better? How the hell does Netflix serve HQ video content instantly?? `sobs in developer`

**Comment by MacKenzieRose** [comment]
> Weird about the files, this is what I see:
> 
> ![Screen Shot 2021-04-15 at 10 14 02 PM](https://user-images.githubusercontent.com/105192/114961985-e8bca880-9e37-11eb-8094-d7f968033bd9.png)

Went and removed those! If you see any others, please let me know! I wasn't meaning to create a file nightmare 🤡

**Comment by thomasjbradley** [comment]
> So the intro videos are definitely the worst offenders; for the ones that are still over 100MB after the first Handbrake compression, do you think I should recompress them at 720p? Could we do something like srcset and sizes but for video, so the mobile load is better?

That’s an amazing idea! And yeah, we can do exactly the same thing for video that we can for the `<picture>` tag:

```html
<video controls loop playsinline class="push">
  <source
    srcset="small.mp4 1280w, large.mp4 1920w"
    sizes="(min-width: 60em) 50vw, (min-width: 38em) 80vw, 100vw"
    type="video/mp4">
  <track>
</video>
```

*The sizes attribute media queries are made up! You’ll have to change it match how much space the video takes up of the width of the screen for each breakpoint.*

> How the hell does Netflix serve HQ video content instantly??

Likely they have faster, dedicated servers. And as far as I know their videos are distributed around the world more thoroughly so they’re always loading more geographically closer.

**Comment by MacKenzieRose** [comment]
> > So the intro videos are definitely the worst offenders; for the ones that are still over 100MB after the first Handbrake compression, do you think I should recompress them at 720p? Could we do something like srcset and sizes but for video, so the mobile load is better?
> 
> That’s an amazing idea! And yeah, we can do exactly the same thing for video that we can for the `<picture>` tag:
> 
> ```
> <video controls loop playsinline class="push">
>   <source
>     srcset="small.mp4 1280w, large.mp4 1920w"
>     sizes="(min-width: 60em) 50vw, (min-width: 38em) 80vw, 100vw"
>     type="video/mp4">
>   <track>
> </video>
> ```
> 
> _The sizes attribute media queries are made up! You’ll have to change it match how much space the video takes up of the width of the screen for each breakpoint._
> 
> > How the hell does Netflix serve HQ video content instantly??
> 
> Likely they have faster, dedicated servers. And as far as I know their videos are distributed around the world more thoroughly so they’re always loading more geographically closer.

@JessJodoin If you feel like tackling something really major today, setting up the intro videos for breakpoints would be dope, and then I can export several versions and upload them to our CDN tomorrow 😸

**Comment by JessJodoin** [comment]
on it boss! 😈

**Comment by MacKenzieRose** [comment]
@thomasjbradley 

It looks like the small videos aren't loading, even in small viewports (snapshot from test in Desktop Chrome)
<img width="1224" alt="Screen Shot 2021-04-19 at 6 56 18 AM" src="https://user-images.githubusercontent.com/19557909/115225781-7ddfcb80-a0dc-11eb-870b-764cb7d0a579.png">

---
I'll check again in half an hour or so to make sure it's not because I didn't wait long enough after uploading them, but if that's not the case, any thoughts?

**Comment by thomasjbradley** [comment]
Delete the `src` attribute, we only want to use `srcset`:
https://github.com/algonquindesign-grads/2021/blob/main/_patterns/sections/layout1-video-section.html#L7

This should be `1280w` not `800w` because the videos are that pixel width.
https://github.com/algonquindesign-grads/2021/blob/main/_patterns/sections/layout1-video-section.html#L8

**Comment by MacKenzieRose** [comment]
> Delete the `src` attribute, we only want to use `srcset`:
> https://github.com/algonquindesign-grads/2021/blob/main/_patterns/sections/layout1-video-section.html#L7

I can't get the videos to load at all on desktop Chrome or Firefox without also including `src` ; I would be surprised, but do these browsers not support `srcset`?

I've made sure that both sizes of the video work when set as `src` so I'm confident it's not the mp4 files; have we done the syntax wrong?

**Comment by thomasjbradley** [comment]
Yeah. So I was totally wrong. The `srcset` & `sizes` attributes don’t work on `<video>`. You can read the current proposal here: https://github.com/filamentgroup/html-video-responsive

I do have a solution for you, with a little bit of JavaScript:

```html
<video controls>
  <source src="hannah-s.mp4" data-hd="hannah.mp4" type="video/mp4">
</video>
```

- The source `src` points to the small version of the video
- The made-up `data-hd` attribute points to the large version of the video

Then, with a titch of JavaScript we can detect the screen width & swap the video:

```js
if (window.matchMedia("(min-width: 60em)").matches) {
  const videos = document.querySelectorAll("source[data-hd]");
  [].forEach.call(videos, (elem) => {
    elem.src = elem.dataset.hd;
  });
}
```

It’s not quite as elegant because small screens will be forced to get the small video, but it’s okay.

What do you think? @MacKenzieRose @JessJodoin

**Comment by MacKenzieRose** [comment]
I don't mind it; let's give it a try~

**Comment by JessJodoin** [comment]
It may not be pretty, but it does the thing!

**Comment by MacKenzieRose** [comment]
This is part of the new PR so I'm closing this issue; will reopen if something breaks on the live site 😄
